'use strict';
const $=id=>document.getElementById(id);
const colors={'재개발':'#ce684e','재건축':'#447cba','신속통합기획':'#bd8b32','모아타운':'#368d71'};
const state={all:[],filtered:[],map:null,layer:null,info:null,selected:null,meta:null,byId:new Map()};
const esc=v=>String(v??'자료 없음').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>v.replace(/\s/g,'').toLowerCase();
function status(message){$('status').textContent=message;}
function options(id,values){for(const value of [...new Set(values)].sort((a,b)=>a.localeCompare(b,'ko'))){const o=document.createElement('option');o.value=value;o.textContent=value;$(id).append(o);}}
function detailHTML(f){const p=f.properties;return `<div class="details"><span class="badge" style="background:${colors[p.type]}">${esc(p.type)}</span><h2>${esc(p.name)}</h2><p class="sub">${esc(p.district)} · ${esc(p.subtype)}</p><dl><dt>사업단계</dt><dd>${esc(p.stage)}</dd><dt>세대수</dt><dd>자료 없음<small> (원본 미제공)</small></dd><dt>원본 기재 면적</dt><dd>${p.source_area_m2?p.source_area_m2.toLocaleString('ko-KR')+' ㎡':'자료 없음'}</dd><dt>자료 공개본</dt><dd>${esc(p.source_release)}</dd><dt>원본 날짜 필드</dt><dd>${esc(p.record_date)}<br><small>CREATE_DAT · 인허가일로 해석하지 않음</small></dd></dl>${p.related_records.length?`<p class="fine"><b>같은 이름의 재정비촉진구역 원본 항목</b><br>${p.related_records.map(r=>`${esc(r.type)}: ${esc(r.stage)} (${esc(r.stage_code)})`).join('<br>')}<br>분류별 기재 단계가 다를 수 있습니다. 최신 단계는 공식 사업정보에서 확인하세요.</p>`:''}<div class="links"><a href="${p.source_url}" target="_blank" rel="noopener">공식 공간자료 ↗</a><a href="https://cleanup.seoul.go.kr/" target="_blank" rel="noopener">정비사업 정보몽땅 ↗</a></div><p class="fine">정보몽땅은 통합 홈페이지입니다. 구역명으로 검색하세요.<br>서울시 참고용 사업 경계로 법적 효력이 없습니다. 신속통합기획·모아타운 경계는 법정 정비구역과 다를 수 있습니다. 사업단계는 이 공개본의 기재값이며 실시간 정보가 아닙니다.<br>출처: 서울특별시 · 공공누리 제4유형<br>원본 ID: ${esc(p.source_id)}</p></div>`;}
function openDetail(f){$('detail-content').innerHTML=detailHTML(f);$('detail').showModal();}
function bounds(features){const b=new naver.maps.LatLngBounds();for(const f of features){b.extend(new naver.maps.LatLng(f.bbox[1],f.bbox[0]));b.extend(new naver.maps.LatLng(f.bbox[3],f.bbox[2]));}return b;}
function fit(){if(state.map&&state.filtered.length)state.map.fitBounds(bounds(state.filtered),{top:85,right:45,bottom:80,left:35});}
function selectFeature(f,position){state.selected=f.id;if(!state.map){openDetail(f);return;}state.layer.setStyle(style);if(!position)state.map.fitBounds(bounds([f]),{top:110,right:60,bottom:90,left:50});const p=f.properties;const box=document.createElement('div');box.className='popup';box.innerHTML=`<strong>${esc(p.name)}</strong><br>${esc(p.district)} · ${esc(p.subtype)}<br>사업단계: ${esc(p.stage)}<br><small>공개본 ${esc(p.source_release)} 기준</small>`;const button=document.createElement('button');button.textContent='상세정보 · 공식 출처';button.addEventListener('click',()=>openDetail(f));box.append(button);state.info.setContent(box);state.info.open(state.map,position||new naver.maps.LatLng(p.anchor[1],p.anchor[0]));document.querySelectorAll('.result').forEach(el=>el.classList.toggle('selected',el.dataset.id===f.id));}
function style(feature){const p=feature.getProperty('type');const selected=feature.getId()===state.selected;return{fillColor:colors[p]||'#777',fillOpacity:selected?.65:.28,strokeColor:colors[p]||'#777',strokeWeight:selected?3:1.5,strokeOpacity:.9,clickable:true};}
function renderMap(){if(!state.layer)return;const old=[];state.layer.forEach(f=>old.push(f));old.forEach(f=>state.layer.removeFeature(f));state.layer.addGeoJson({type:'FeatureCollection',features:state.filtered});state.layer.setStyle(style);}
function filter(){const query=norm($('search').value);state.filtered=state.all.filter(f=>{const p=f.properties;return (!query||norm(p.name).includes(query))&&(!$('district').value||p.district===$('district').value)&&(!$('type').value||p.type===$('type').value)&&(!$('stage').value||p.stage===$('stage').value);});state.selected=null;if(state.info)state.info.close();$('count').textContent=`${state.filtered.length.toLocaleString('ko-KR')}건 / 전체 ${state.all.length.toLocaleString('ko-KR')}건`;$('fit').disabled=!state.filtered.length;const frag=document.createDocumentFragment();for(const f of state.filtered){const p=f.properties;const b=document.createElement('button');b.className='result';b.dataset.id=f.id;b.innerHTML=`<span class="dot" style="background:${colors[p.type]}"></span><span><strong>${esc(p.name)}</strong><small>${esc(p.district)} · ${esc(p.subtype)}<br>${esc(p.stage)}</small></span><span class="arrow" aria-hidden="true">↗</span>`;b.addEventListener('click',()=>selectFeature(f));frag.append(b);}$('results').replaceChildren(frag);if(!state.filtered.length)$('results').innerHTML='<p class="empty">검색 결과가 없습니다.<br>구역명을 줄이거나 필터를 초기화해 주세요.</p>';renderMap();}
async function loadMap(){return new Promise((resolve,reject)=>{window.navermap_authFailure=()=>{reject(Error('NAVER 지도 인증 실패: Dynamic Map 활성화와 Web Service URL http://localhost:8000 등록을 확인하세요. 목록과 상세정보는 계속 사용할 수 있습니다.'));};window.initNaver=()=>resolve();const s=document.createElement('script');s.src='https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=zhvmg0rp93&callback=initNaver';s.onerror=()=>reject(Error('NAVER 지도를 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.'));document.head.append(s);setTimeout(()=>{if(!window.naver?.maps)reject(Error('NAVER 지도 응답이 없습니다. 인터넷 연결·Client ID·허용 URL을 확인하세요.'));},20000);});}
async function start(){try{const [geo,meta]=await Promise.all(['data/projects.geojson','data/metadata.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error(u+' 파일을 불러올 수 없습니다.');return r.json();}));state.all=geo.features;state.meta=meta;state.byId=new Map(state.all.map(f=>[f.id,f]));$('release').textContent=meta.release_date;options('district',state.all.map(f=>f.properties.district));options('type',Object.keys(colors));options('stage',state.all.map(f=>f.properties.stage));filter();status('경계 자료를 준비했습니다. NAVER 지도를 불러오는 중입니다.');await loadMap();state.map=new naver.maps.Map('map',{center:new naver.maps.LatLng(37.545,126.99),zoom:12,zoomControl:true,zoomControlOptions:{position:naver.maps.Position.TOP_RIGHT},mapDataControl:true,scaleControl:true});state.layer=state.map.data;state.info=new naver.maps.InfoWindow({borderWidth:0,backgroundColor:'#fff',anchorSize:new naver.maps.Size(12,8)});naver.maps.Event.addListener(state.layer,'click',e=>{const f=state.byId.get(e.feature.getId());if(f)selectFeature(f,e.coord);});naver.maps.Event.addListener(state.map,'click',()=>state.info.close());renderMap();status('');new ResizeObserver(()=>{const center=state.map.getCenter();state.map.setSize(new naver.maps.Size($('map').clientWidth,$('map').clientHeight));state.map.setCenter(center);}).observe($('map'));}catch(e){status(e.message+' 파일을 더블클릭하지 말고 폴더에서 python3 -m http.server 8000을 실행한 뒤 http://localhost:8000으로 접속하세요.');}}
$('legend-items').innerHTML=Object.entries(colors).map(([name,color])=>`<span><i style="background:${color}"></i>${name}</span>`).join('');
let timer;$('search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(filter,160);});for(const id of ['district','type','stage'])$(id).addEventListener('change',filter);$('search').addEventListener('keydown',e=>{if(e.key==='Enter'){filter();fit();}});document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{for(const id of ['district','type','stage'])$(id).value='';$('search').value=b.dataset.query;filter();fit();}));$('reset').addEventListener('click',()=>{for(const id of ['search','district','type','stage'])$(id).value='';filter();});$('fit').addEventListener('click',fit);$('home').addEventListener('click',()=>{if(state.map)state.map.fitBounds(bounds(state.all),{top:70,right:50,bottom:70,left:30});});$('toggle').addEventListener('click',()=>{const closed=document.body.classList.toggle('collapsed');$('toggle').textContent=closed?'목록 열기':'목록 접기';$('toggle').setAttribute('aria-expanded',String(!closed));});$('detail').querySelector('.close').addEventListener('click',()=>$('detail').close());start();
